title : Let there be light!
tagline: "Blogging about computers, language, music, politics and what have you"
author :
  name : Pierpaolo Frasa
  github : Fryie
  twitter : Tainnor

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
